# Generated by Django 3.2.4 on 2023-05-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogStatements',
        ),
        migrations.DeleteModel(
            name='LogStatementsChanges',
        ),
    ]
